/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2022-08-22T22:50:27.287+01:00
  3.36.1.4
  
  Standalone prediction code with sample test data for XGBoostModel named HeartFailureComplications

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/HeartFailureComplications > HeartFailureComplications.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m HeartFailureComplications.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
package org.apache.storm.starter;
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="HeartFailureComplications", algorithm="xgboost")
public class HeartFailureComplications extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Binomial; }

  public boolean isSupervised() { return true; }
  public int nclasses() { return 2; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_HeartFailureComplications.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 2;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* age */ null,
    /* anemia */ null,
    /* creatinine_phosphokinase */ null,
    /* diabetes */ null,
    /* ejection_fraction */ null,
    /* high_blood_pressure */ null,
    /* platelets */ null,
    /* serum_creatinine */ null,
    /* serum_sodium */ null,
    /* sex */ null,
    /* smoking */ null,
    /* time */ null,
    /* complications */ HeartFailureComplications_ColInfo_12.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.6789297658862876,0.3210702341137124};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = null;

  public HeartFailureComplications() { super(NAMES,DOMAINS,"complications"); }
  public String getUUID() { return Long.toString(303063250709419333L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    float preds_0 = 0f;
    preds_0 += HeartFailureComplications_Tree_g_0_t_0.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_1.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_2.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_3.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_4.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_5.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_6.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_7.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_8.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_9.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_10.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_11.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_12.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_13.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_14.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_15.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_16.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_17.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_18.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_19.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_20.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_21.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_22.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_23.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_24.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_25.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_26.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_27.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_28.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_29.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_30.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_31.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_32.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_33.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_34.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_35.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_36.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_37.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_38.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_39.score0(data);
    preds_0 += HeartFailureComplications_Tree_g_0_t_40.score0(data);
    preds_0 += -0.0f;
    preds[0] = preds_0;
    preds[0] = (float) 1f/(1f + (float)Math.min(1e19, Math.exp(-(preds[0]))));
    preds[1] = 1f - preds[0];
    preds[2] = preds[0];
    preds[0] = GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.47977161407470703);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_HeartFailureComplications implements java.io.Serializable {
  public static final String[] VALUES = new String[12];
  static {
    NamesHolder_HeartFailureComplications_0.fill(VALUES);
  }
  static final class NamesHolder_HeartFailureComplications_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "age";
      sa[1] = "anemia";
      sa[2] = "creatinine_phosphokinase";
      sa[3] = "diabetes";
      sa[4] = "ejection_fraction";
      sa[5] = "high_blood_pressure";
      sa[6] = "platelets";
      sa[7] = "serum_creatinine";
      sa[8] = "serum_sodium";
      sa[9] = "sex";
      sa[10] = "smoking";
      sa[11] = "time";
    }
  }
}
// The class representing column complications
class HeartFailureComplications_ColInfo_12 implements java.io.Serializable {
  public static final String[] VALUES = new String[2];
  static {
    HeartFailureComplications_ColInfo_12_0.fill(VALUES);
  }
  static final class HeartFailureComplications_ColInfo_12_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "0";
      sa[1] = "1";
    }
  }
}

class HeartFailureComplications_Tree_g_0_t_0 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[7]) || ((float)data[7]) < 1.55f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 76.0f) ?
        ((Double.isNaN(data[7]) || ((float)data[7]) < 1.19f) ?
          ((Double.isNaN(data[7]) || ((float)data[7]) < 0.95f) ?
            ((Double.isNaN(data[6]) || ((float)data[6]) < 207500.0f) ?
              -0.22105263f
              :
              -0.51111114f
            )
            :
            ((Double.isNaN(data[6]) || ((float)data[6]) < 309500.0f) ?
              -0.39310345f
              :
              -0.10000001f
            )
          )
          :
          ((Double.isNaN(data[10]) || ((float)data[10]) < 0.5f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
              -0.38823533f
              :
              -0.13333334f
            )
            :
            0.075f
          )
        )
        :
        0.075f
      )
      :
      ((Double.isNaN(data[8]) || ((float)data[8]) < 135.5f) ?
        0.27567568f
        :
        -0.10000001f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_1 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 73.5f) ?
      ((Double.isNaN(data[6]) || ((float)data[6]) < 299500.0f) ?
        0.47471324f
        :
        0.2110758f
      )
      :
      ((Double.isNaN(data[7]) || ((float)data[7]) < 1.45f) ?
        -0.43241745f
        :
        ((Double.isNaN(data[11]) || ((float)data[11]) < 183.0f) ?
          0.118021406f
          :
          -0.21426933f
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_2 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 67.5f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 67.5f) ?
        0.273533f
        :
        ((Double.isNaN(data[4]) || ((float)data[4]) < 32.5f) ?
          ((Double.isNaN(data[11]) || ((float)data[11]) < 183.0f) ?
            0.09988496f
            :
            -0.16923374f
          )
          :
          -0.41990295f
        )
      )
      :
      ((Double.isNaN(data[11]) || ((float)data[11]) < 73.5f) ?
        0.385862f
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 71.0f) ?
          -0.30016956f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 76.0f) ?
            0.02120361f
            :
            -0.15098527f
          )
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_3 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[7]) || ((float)data[7]) < 1.815f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 59.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 163.5f) ?
          0.14517792f
          :
          0.3143654f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 765.0f) ?
          ((Double.isNaN(data[7]) || ((float)data[7]) < 1.3499999f) ?
            -0.32939115f
            :
            -0.17093384f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 1814.0f) ?
            -0.12116472f
            :
            -0.049711812f
          )
        )
      )
      :
      ((Double.isNaN(data[7]) || ((float)data[7]) < 2.25f) ?
        0.27696663f
        :
        -0.01746409f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_4 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[7]) || ((float)data[7]) < 1.19f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 1861.0f) ?
        ((Double.isNaN(data[4]) || ((float)data[4]) < 32.5f) ?
          -0.10419271f
          :
          ((Double.isNaN(data[5]) || ((float)data[5]) < 0.5f) ?
            -0.27516225f
            :
            ((Double.isNaN(data[6]) || ((float)data[6]) < 274500.0f) ?
              -0.2290471f
              :
              -0.05469995f
            )
          )
        )
        :
        0.05382112f
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 68.5f) ?
        ((Double.isNaN(data[6]) || ((float)data[6]) < 228000.0f) ?
          0.083341435f
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 293.0f) ?
            -0.10401689f
            :
            -0.26798412f
          )
        )
        :
        ((Double.isNaN(data[7]) || ((float)data[7]) < 1.865f) ?
          0.2330952f
          :
          0.0710615f
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_5 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 73.5f) ?
      ((Double.isNaN(data[8]) || ((float)data[8]) < 138.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 235.0f) ?
          0.018694015f
          :
          0.29296306f
        )
        :
        0.3618609f
      )
      :
      ((Double.isNaN(data[7]) || ((float)data[7]) < 1.55f) ?
        ((Double.isNaN(data[11]) || ((float)data[11]) < 173.0f) ?
          ((Double.isNaN(data[6]) || ((float)data[6]) < 227000.0f) ?
            0.03192583f
            :
            -0.29196584f
          )
          :
          -0.34651253f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 327.0f) ?
          -0.061145548f
          :
          0.15934527f
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_6 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[4]) || ((float)data[4]) < 27.5f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 254.0f) ?
        0.13157064f
        :
        0.31562495f
      )
      :
      ((Double.isNaN(data[8]) || ((float)data[8]) < 134.5f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 0.5f) ?
          0.22383735f
          :
          -0.13361335f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 120.0f) ?
          -0.34282923f
          :
          ((Double.isNaN(data[9]) || ((float)data[9]) < 0.5f) ?
            0.056400213f
            :
            ((Double.isNaN(data[6]) || ((float)data[6]) < 271500.0f) ?
              -0.21798067f
              :
              -0.10188874f
            )
          )
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_7 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[4]) || ((float)data[4]) < 22.5f) ?
      0.23578258f
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 79.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 80.5f) ?
          -0.39127892f
          :
          ((Double.isNaN(data[9]) || ((float)data[9]) < 0.5f) ?
            ((Double.isNaN(data[7]) || ((float)data[7]) < 1.25f) ?
              -0.06942017f
              :
              0.29857376f
            )
            :
            ((Double.isNaN(data[6]) || ((float)data[6]) < 309500.0f) ?
              -0.17698288f
              :
              0.06383948f
            )
          )
        )
        :
        0.10293318f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_8 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 68.5f) ?
      ((Double.isNaN(data[6]) || ((float)data[6]) < 311500.0f) ?
        ((Double.isNaN(data[6]) || ((float)data[6]) < 210500.0f) ?
          0.028371476f
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 237.5f) ?
            -0.12991841f
            :
            -0.29958615f
          )
        )
        :
        ((Double.isNaN(data[4]) || ((float)data[4]) < 36.5f) ?
          0.20624684f
          :
          -0.14133395f
        )
      )
      :
      ((Double.isNaN(data[7]) || ((float)data[7]) < 1.19f) ?
        -0.03138879f
        :
        ((Double.isNaN(data[8]) || ((float)data[8]) < 134.5f) ?
          0.041812263f
          :
          0.21903265f
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_9 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 173.0f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 67.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 127.5f) ?
          0.054836664f
          :
          0.26289815f
        )
        :
        ((Double.isNaN(data[11]) || ((float)data[11]) < 120.5f) ?
          ((Double.isNaN(data[7]) || ((float)data[7]) < 1.25f) ?
            -0.24033482f
            :
            -0.014002565f
          )
          :
          0.27074102f
        )
      )
      :
      -0.26049313f
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_10 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[8]) || ((float)data[8]) < 135.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 74.0f) ?
        ((Double.isNaN(data[6]) || ((float)data[6]) < 217500.0f) ?
          0.1372245f
          :
          -0.03599572f
        )
        :
        0.22529058f
      )
      :
      ((Double.isNaN(data[4]) || ((float)data[4]) < 27.5f) ?
        0.14902377f
        :
        ((Double.isNaN(data[6]) || ((float)data[6]) < 198500.0f) ?
          0.023034515f
          :
          ((Double.isNaN(data[6]) || ((float)data[6]) < 319000.0f) ?
            ((Double.isNaN(data[4]) || ((float)data[4]) < 36.5f) ?
              -0.29688793f
              :
              -0.09184997f
            )
            :
            -0.040800564f
          )
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_11 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 52.0f) ?
      0.2142805f
      :
      ((Double.isNaN(data[4]) || ((float)data[4]) < 27.5f) ?
        0.19428955f
        :
        ((Double.isNaN(data[8]) || ((float)data[8]) < 135.5f) ?
          ((Double.isNaN(data[11]) || ((float)data[11]) < 167.0f) ?
            0.074713126f
            :
            -0.107748434f
          )
          :
          ((Double.isNaN(data[10]) || ((float)data[10]) < 0.5f) ?
            -0.18272127f
            :
            -0.3252328f
          )
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_12 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 73.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 59.0f) ?
        0.036454435f
        :
        0.19323114f
      )
      :
      ((Double.isNaN(data[7]) || ((float)data[7]) < 1.19f) ?
        ((Double.isNaN(data[6]) || ((float)data[6]) < 221500.0f) ?
          -0.083145775f
          :
          -0.22739032f
        )
        :
        ((Double.isNaN(data[9]) || ((float)data[9]) < 0.5f) ?
          0.12751713f
          :
          ((Double.isNaN(data[11]) || ((float)data[11]) < 158.0f) ?
            -0.1599023f
            :
            0.03876592f
          )
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_13 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[4]) || ((float)data[4]) < 32.5f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 82.5f) ?
        0.20571692f
        :
        ((Double.isNaN(data[6]) || ((float)data[6]) < 262679.0f) ?
          -0.06340223f
          :
          0.117523156f
        )
      )
      :
      ((Double.isNaN(data[11]) || ((float)data[11]) < 49.5f) ?
        0.25339842f
        :
        ((Double.isNaN(data[9]) || ((float)data[9]) < 0.5f) ?
          -0.06893731f
          :
          -0.26053923f
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_14 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 182.5f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 103.0f) ?
        -0.11978216f
        :
        ((Double.isNaN(data[11]) || ((float)data[11]) < 124.5f) ?
          ((Double.isNaN(data[11]) || ((float)data[11]) < 78.5f) ?
            ((Double.isNaN(data[6]) || ((float)data[6]) < 264179.0f) ?
              0.07610357f
              :
              0.24510439f
            )
            :
            -0.031143358f
          )
          :
          0.31029063f
        )
      )
      :
      ((Double.isNaN(data[4]) || ((float)data[4]) < 32.5f) ?
        -0.10749244f
        :
        -0.26193896f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_15 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 52.0f) ?
      0.09027456f
      :
      ((Double.isNaN(data[4]) || ((float)data[4]) < 32.5f) ?
        ((Double.isNaN(data[7]) || ((float)data[7]) < 1.3499999f) ?
          -0.062258422f
          :
          0.15318234f
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
          -0.11221204f
          :
          -0.3068152f
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_16 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 199.5f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 149.0f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 68.5f) ?
          ((Double.isNaN(data[11]) || ((float)data[11]) < 82.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 58.0f) ?
              -0.06284406f
              :
              0.09610693f
            )
            :
            -0.22511327f
          )
          :
          0.09958561f
        )
        :
        0.19528364f
      )
      :
      -0.20584439f
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_17 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 127.5f) ?
      -0.099595584f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 594.5f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 0.5f) ?
          ((Double.isNaN(data[6]) || ((float)data[6]) < 236000.0f) ?
            0.2938304f
            :
            0.12457937f
          )
          :
          0.0070113763f
        )
        :
        -0.042036537f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_18 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[4]) || ((float)data[4]) < 32.5f) ?
      ((Double.isNaN(data[7]) || ((float)data[7]) < 1.05f) ?
        -0.026263647f
        :
        ((Double.isNaN(data[11]) || ((float)data[11]) < 112.0f) ?
          0.07120013f
          :
          0.26497605f
        )
      )
      :
      ((Double.isNaN(data[11]) || ((float)data[11]) < 49.5f) ?
        0.15605497f
        :
        ((Double.isNaN(data[9]) || ((float)data[9]) < 0.5f) ?
          0.019776274f
          :
          -0.1968232f
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_19 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[7]) || ((float)data[7]) < 0.95f) ?
      -0.18059242f
      :
      ((Double.isNaN(data[11]) || ((float)data[11]) < 171.5f) ?
        ((Double.isNaN(data[6]) || ((float)data[6]) < 307500.0f) ?
          ((Double.isNaN(data[8]) || ((float)data[8]) < 136.5f) ?
            0.16053641f
            :
            -0.14333883f
          )
          :
          0.22521263f
        )
        :
        -0.09121222f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_20 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[8]) || ((float)data[8]) < 139.5f) ?
      ((Double.isNaN(data[6]) || ((float)data[6]) < 210500.0f) ?
        0.12625764f
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 127.5f) ?
          -0.22642456f
          :
          ((Double.isNaN(data[3]) || ((float)data[3]) < 0.5f) ?
            0.07418063f
            :
            -0.13231836f
          )
        )
      )
      :
      0.113351636f
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_21 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[6]) || ((float)data[6]) < 272500.0f) ?
      ((Double.isNaN(data[6]) || ((float)data[6]) < 218500.0f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 239.0f) ?
          -0.1599383f
          :
          0.088715106f
        )
        :
        0.13882372f
      )
      :
      ((Double.isNaN(data[6]) || ((float)data[6]) < 318500.0f) ?
        -0.27177006f
        :
        0.027471896f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_22 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 232.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 67.5f) ?
        ((Double.isNaN(data[6]) || ((float)data[6]) < 219500.0f) ?
          -0.052283075f
          :
          -0.17813192f
        )
        :
        0.03559713f
      )
      :
      ((Double.isNaN(data[11]) || ((float)data[11]) < 108.5f) ?
        -0.027175425f
        :
        0.1460204f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_23 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 49.5f) ?
      0.12276367f
      :
      ((Double.isNaN(data[9]) || ((float)data[9]) < 0.5f) ?
        0.02155808f
        :
        ((Double.isNaN(data[7]) || ((float)data[7]) < 1.25f) ?
          -0.038794287f
          :
          -0.20062418f
        )
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_24 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 173.0f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 108.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 128.0f) ?
          -0.07129886f
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 332.0f) ?
            0.1988041f
            :
            -0.05982391f
          )
        )
        :
        0.18363072f
      )
      :
      -0.10954099f
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_25 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[7]) || ((float)data[7]) < 1.55f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 78.5f) ?
        0.11003721f
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 376.5f) ?
          -0.2613264f
          :
          -0.037673857f
        )
      )
      :
      ((Double.isNaN(data[6]) || ((float)data[6]) < 226000.0f) ?
        0.14668639f
        :
        0.010080504f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_26 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[8]) || ((float)data[8]) < 134.5f) ?
      0.115079306f
      :
      ((Double.isNaN(data[8]) || ((float)data[8]) < 139.5f) ?
        ((Double.isNaN(data[4]) || ((float)data[4]) < 32.5f) ?
          0.0143825505f
          :
          -0.108712554f
        )
        :
        0.1072253f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_27 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 196.5f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 149.0f) ?
        ((Double.isNaN(data[11]) || ((float)data[11]) < 78.5f) ?
          ((Double.isNaN(data[4]) || ((float)data[4]) < 36.5f) ?
            0.19482219f
            :
            -0.04600843f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 548.0f) ?
            -0.11682023f
            :
            -0.006856186f
          )
        )
        :
        0.21669525f
      )
      :
      -0.14768192f
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_28 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[8]) || ((float)data[8]) < 134.5f) ?
      ((Double.isNaN(data[7]) || ((float)data[7]) < 1.3499999f) ?
        -0.015197042f
        :
        0.16113155f
      )
      :
      ((Double.isNaN(data[11]) || ((float)data[11]) < 124.5f) ?
        ((Double.isNaN(data[7]) || ((float)data[7]) < 1.14f) ?
          -0.015000067f
          :
          -0.15750465f
        )
        :
        0.07034077f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_29 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[8]) || ((float)data[8]) < 134.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 65.5f) ?
        0.12480498f
        :
        -0.061313294f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 0.5f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
          -0.18267694f
          :
          -0.050497938f
        )
        :
        0.04254236f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_30 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[11]) || ((float)data[11]) < 173.0f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 127.5f) ?
        -0.09277921f
        :
        ((Double.isNaN(data[4]) || ((float)data[4]) < 32.5f) ?
          0.036900196f
          :
          0.1502171f
        )
      )
      :
      -0.13746044f
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_31 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 765.0f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 331.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 103.5f) ?
          -0.07424356f
          :
          0.09530788f
        )
        :
        -0.15396897f
      )
      :
      0.08206584f
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_32 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[7]) || ((float)data[7]) < 0.95f) ?
      -0.17974296f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 600.0f) ?
        ((Double.isNaN(data[7]) || ((float)data[7]) < 1.45f) ?
          0.019542428f
          :
          0.18493848f
        )
        :
        -0.07463697f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_33 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[7]) || ((float)data[7]) < 1.14f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 78.5f) ?
        0.1770011f
        :
        -0.004469076f
      )
      :
      ((Double.isNaN(data[6]) || ((float)data[6]) < 229500.0f) ?
        0.074325435f
        :
        -0.16342749f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_34 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 98.0f) ?
      -0.15346465f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 0.5f) ?
        ((Double.isNaN(data[7]) || ((float)data[7]) < 1.19f) ?
          -0.0029491673f
          :
          0.20526366f
        )
        :
        -0.058850624f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_35 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[6]) || ((float)data[6]) < 305500.0f) ?
      ((Double.isNaN(data[4]) || ((float)data[4]) < 39.0f) ?
        ((Double.isNaN(data[7]) || ((float)data[7]) < 1.14f) ?
          0.10640214f
          :
          -0.097414896f
        )
        :
        -0.117272295f
      )
      :
      0.09898789f
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_36 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[7]) || ((float)data[7]) < 1.05f) ?
      -0.081813425f
      :
      ((Double.isNaN(data[8]) || ((float)data[8]) < 136.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 454.5f) ?
          0.16982785f
          :
          -0.025406586f
        )
        :
        -0.037658744f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_37 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 53.5f) ?
      -0.09300157f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 470.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 127.5f) ?
          -0.0039691357f
          :
          0.17357796f
        )
        :
        -0.061668295f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_38 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 257.5f) ?
      ((Double.isNaN(data[11]) || ((float)data[11]) < 92.0f) ?
        0.007545155f
        :
        -0.10424521f
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 59.5f) ?
        0.15223342f
        :
        -0.055344127f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_39 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[8]) || ((float)data[8]) < 132.5f) ?
      0.09125571f
      :
      ((Double.isNaN(data[8]) || ((float)data[8]) < 138.5f) ?
        ((Double.isNaN(data[6]) || ((float)data[6]) < 217500.0f) ?
          0.037456874f
          :
          ((Double.isNaN(data[6]) || ((float)data[6]) < 275000.0f) ?
            -0.07774432f
            :
            -0.18489565f
          )
        )
        :
        0.040325537f
      )
    );
  }
}

class HeartFailureComplications_Tree_g_0_t_40 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[7]) || ((float)data[7]) < 2.0f) ?
      ((Double.isNaN(data[8]) || ((float)data[8]) < 137.5f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
          0.031163277f
          :
          0.1944692f
        )
        :
        -0.040953595f
      )
      :
      -0.090165935f
    );
  }
}

